spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/votacao-dev?currentSchema=dev
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: dev
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: '/api'

logging:
  level:
    br.com.gabrielferreira.votacao: DEBUG
    org:
      flywaydb: INFO